name: Report a bug of the ClashT core
description: Create a bug report to help us improve
labels:
  - bug
title: "<issue title>"
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for taking the time to report an issue with the ClashT core.  
        
        Prior to submitting this issue, please read and follow the guidelines below to ensure that your issue can be resolved as quickly as possible. Options marked with an asterisk (*) are required, while others are optional. If the information you provide does not comply with the requirements, we may not respond or close the issue 
        directly.  
        
        <small>If you can debug and fix the issue yourself, we welcome you to submit a pull request to merge your changes.</small>

        ### Prerequisites
        1. I understand that this is the official open-source version of the ClashT core, only providing support for the Open-source version or Premium version.
        2. I am submitting an issue with the ClashT core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version.
        3. I have searched and have not found any similar issues.
        4. I have read the [official Wiki](https://clasht.drypeng.io/) or discussed with people in [Discussions](https://github.com/DryPeng/clashT/discussions) confirmed this is a bug.

  - type: markdown
    attributes:
      value: "## Environment"
  - type: markdown
    attributes:
      value: |
        Please provide the following information to help us locate the issue.  
        The issue might be closed if there's not enough information provided.

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: "Run `ClashT -v` or look at the bottom-left corner of the ClashT Dashboard to find out"
      options:
        - v1.20.0 (NEW)
        - v1.19.0
        - v1.18.1
        - v1.18.0        
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: "Select all operating systems that apply to this issue"
      multiple: true
      options:
        - Android
        - Linux
        - macOS (darwin)
        - OpenBSD / FreeBSD
        - Windows
        
  - type: dropdown
    id: arch
    attributes:
      label: Architecture
      description: "Select all architectures that apply to this issue"
      multiple: true
      options:
        - amd64
        - amd64-v3
        - arm64
        - armv5
        - armv6
        - armv7
        - i386
        - mips-hardfloat
        - mips-softfloat
        - mipsle-hardfloat
        - mipsle-softfloat
        - mips64
        - mips64le
        - riscv64

  - type: markdown
    attributes:
      value: "## ClashT related information"
  - type: markdown
    attributes:
      value: |
        Please provide relevant information about your ClashT instance here. 
        If you do not provide enough information, the issue may be closed.

  - type: checkboxes
    id: pcore
    attributes:
      label: Are you using Premium core?
      description: "If bug does not appear on Premium core, please ignore this."
      options:
        - label: "Yes, I am"

  - type: checkboxes
    id: pr
    attributes:
      label: Do you want submit a pull request to merge?
      description: "No need to worry about new bugs appearing, we review every request. (please try to write code that is as easy to read as ours)"
      options:
        - label: "Yes, I do"

  - type: textarea
    attributes:
      render: YAML
      label: Configuration File
      placeholder: "Ensure that there is no sensitive information (such as server addresses, passwords, or ports) in the configuration file, and provide the minimum reproducible configuration. Do not post configurations with thousands of lines."
    validations:
      required: true

  - type: textarea
    attributes:
      render: Text
      label: Log
      placeholder: "Please attach the corresponding core outout (setting `log-level: debug` in the configuration provides debugging information)."

  - type: textarea
    attributes:
      label: Description
      placeholder: "Please describe your issue in detail here to help us understand (supports Markdown syntax)."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      placeholder: "Please provide the specific steps to reproduce the issue here (supports Markdown syntax)."
