blank_issues_enabled: false

contact_links:
  - name: Read our Wiki page
    url: https://clasht.drypeng.io/
    about: If you are new to ClashT, or want to know more about ClashT, please read our Wiki page
  - name: 阅读 Wiki
    url: https://clasht.drypeng.io/zh_CN/
    about: 如果你是新手，或者想要了解 Clash 的更多信息，请阅读我们撰写的官方 Wiki
