name: Feature request
description: Suggest an idea for this project
labels:
  - enhancement
title: "<title>"
body:
  - type: markdown
    attributes:
      value: |
        ### Thank you for taking the time to report an issue with the ClashT core.  
        
        Prior to submitting this issue, please read and follow the guidelines below to ensure that your issue can be resolved as quickly as possible. Options marked with an asterisk (*) are required, while others are optional. If the information you provide does not comply with the requirements, we may not respond or close the issue 
        directly.  
        
        <small>If you can debug and fix the issue yourself, we welcome you to submit a pull request to merge your changes.</small>

        ### Prerequisites
        1. I understand that this is the official open-source version of the ClashT core, only providing support for the Open-source version or Premium version.
        2. I am submitting an feature request with the ClashT core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version.
        3. I have searched and have not found any similar [issues](https://github.com/DryPeng/clashT/issues?q=is%3Aissue+label%3Aenhancement).
        4. I have read the [official Wiki](https://clasht.drypeng.io/).


  - type: textarea
    attributes:
      label: Description
      placeholder: Please explain your suggestions in detail and clearly. For example, "What features would you like?" or "How good is this feature?".
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Possible Solution
      placeholder: "Do you have any ideas on the implementation details?"

