name: Find and Replace
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "Dreamacro/clash"
          replace: "DryPeng/clashT"
          include: "transport/vless/**"
          regex: false
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
