name: Find and Replace
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "ClashTTT"
          replace: "ClashTT"
          include: "docs/*.md"
          regex: false
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "ClashTT"
          replace: "ClashT"
          include: "docs/*.md"
          regex: false
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
