name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: '1.21'
          
      - name: Optic
        uses: evantorrie/mott-the-tidier@v1-beta
        with:
          gomods: |
            **/go.mod
      - uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: Auto-fix go.sum discrepancies

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cache go module
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies, run test
        run: |
          go test ./...

  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: '1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Cache go module
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        env:
          NAME: clash
          BINDIR: bin
        run: make -j $(go run ./test/main.go) all
